### ISSUE TITLE
Using agda-holes

### ISSUE THREAD

**Issue by ajrouvoet** [bch29/agda-holes#1]
I think you have a very nice application of reflection in Agda here and was wondering what the status of this project is nowadays. 

One issue you note in the Readme is that since this is a master's thesis project, you cannot accept contributions. If you've graduated by now, it might be good to update the Readme :)

Cheers,

Arjen

**Comment by bch29** [comment]
Hi Arjen,

Thanks for the kind words :). I haven't worked on this since graduating and I don't know if it still works with current versions of Agda. Feel free to try to use it and I'm happy to help if you run into any issues!

Best,
Brad

**Comment by ajrouvoet** [comment]
Thanks!
